### ISSUE TITLE
Bad context for new tokens

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/smaug#112] opened 2016-05-19 10:53 UTC
I just got a shiny new `access_token` from `auth.dbc.dk`, but when I pass it to a search request on `openplatform.dbc.dk` it errors with `{"statusCode": 500, "error": "TypeError: Cannot read property 'agency' of undefined"}`. (it works fine with an old token...)

**Comment by rasmuserik** [comment] 2016-05-23 07:36
This might also be due to, that I log in as the anonymous user, `@` / `@`

**Comment by adamtulinius** [comment] 2016-05-23 08:30
This is weird, since anonymous logins should cause a default agency/libraryId to be set.
I'll look into it.

**Comment by adamtulinius** [comment] 2016-05-23 11:00
Working as designed; the smaug-config has a specific configuration for library id's "000000" and "000001".
The problem arises because the default library id is also "000000".

The default library id will be set to match search results from bibliotek.dk.

**Comment by adamtulinius** [comment] 2016-05-28 14:29
Closing, since this is also tracked in #124

**Closed** 2016-05-28 14:29 UTC
Labels: bug
